### ISSUE TITLE
Add Descriptions for Concept Diagram and System Flow Chart

### ISSUE THREAD

**Issue by Franlexa** [tinegachris/Smart-Water-Management-System#1]
The project includes Concept Diagram.vsdx and System Flow Chart.vsdx files, but there are no descriptions in the README.md explaining these files or their purpose within the system. Adding a section to the README with descriptions for these diagrams would make the project easier to understand for new users.

**Comment by tinegachris** [comment]
I have updated the README file with details of the .vsdx files in commit b6a544a20f30b0d8233603d55a1956fb811c879e
