### ISSUE TITLE
Provide Installation and Setup Instructions for .aia and .apk Files

### ISSUE THREAD

**Issue by Franlexa** [tinegachris/Smart-Water-Management-System#2]
The project contains Smart_Water_App.aia and Smart_Water_App.apk, but there are no instructions on how to install or use these files. Adding installation steps and usage information to the README.md or a new documentation file would be beneficial for users.

**Comment by tinegachris** [comment]
I have updated the README.md file with commit ID f6b5aaa9426561e8aedb1e591111bee282a13e. Thanks!
